### ISSUE TITLE
Can't parse local dash exception when trying to register DRM protected content

### ISSUE THREAD

**Issue by YHossam** [kaltura/playkit-android#684]
##### Prerequisites
- [x] Have you checked for duplicate [issues](https://github.com/kaltura/playkit-android/issues): Yes
- [x] Which Player [version](https://github.com/kaltura/playkit-android/releases) are you using: 4.9.0
- [x] Can you reproduce the issue with our latest release version: Yes
- [x] Can you reproduce the issue with the latest code from master: Yes
- [x] What devices and OS versions are you using: Devices[Emulator and Xiaomi Five plus], OS [Android 9 and Android 10]
- [x] If applicable, add test code or test page to reproduce: 
```
Paste test code here
localAssetsManager.registerAsset(mediaSource, absolutePath, itemId,
                        object : LocalAssetsManager.AssetRegistrationListener {
                            override fun onFailed(localAssetPath: String?, error: java.lang.Exception?) {
                                Timber.e("Failed to register asset $localAssetPath")
                                Timber.e(error)
                            }

                            override fun onRegistered(localAssetPath: String?) {
                                Timber.d("asset $localAssetPath registered successfully")
                            }

                        })
```
##### Expected behavior
I'm expecting the downloaded media source to be registered, and onRegistered to be called (The media source has DRM Data)

##### Actual behavior
An exception raises and onFailed is called instead
##### Console output
```
com.inmobly.impresa.demo E/DownloadToGoDownloader$registerAsset: Failed to register asset /storage/emulated/0/Android/data/com.inmobly.impresa.demo/files/dtg/clear/items/1_jjrdnbe6/data/master.m3u8
com.inmobly.impresa.demo E/DownloadToGoDownloader$registerAsset: com.kaltura.playkit.LocalAssetsManager$RegisterException: Can't parse local dash
        at com.kaltura.playkit.drm.WidevineModularAdapter.parseDash(WidevineModularAdapter.java:317)
        at com.kaltura.playkit.drm.WidevineModularAdapter.registerAsset(WidevineModularAdapter.java:83)
        at com.kaltura.playkit.drm.WidevineModularAdapter.registerAsset(WidevineModularAdapter.java:67)
        at com.kaltura.playkit.LocalAssetsManager.lambda$registerDrmAsset$1$LocalAssetsManager(LocalAssetsManager.java:187)
        at com.kaltura.playkit.-$$Lambda$LocalAssetsManager$UXre8Mser0kKEryZyd5OpSEhKVQ.run(Unknown Source:12)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.kaltura.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT #EXTM3U
    #EXT-X-S...@4:1 in java.io.InputStreamReader@9ee2be7) 
        at com.kaltura.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:96)
        at com.kaltura.playkit.drm.SimpleDashParser.parse(SimpleDashParser.java:66)
        at com.kaltura.playkit.drm.WidevineModularAdapter.parseDash(WidevineModularAdapter.java:309)
        	... 8 more
     Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT #EXTM3U
    #EXT-X-S...@4:1 in java.io.InputStreamReader@9ee2be7) 
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:440)
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:321)
        at com.kaltura.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:89)
        	... 10 more
```

**Comment by GouravSna** [comment]
Hi @YHossam ,

You are trying to register a HLS media(.m3u8) on android device which is not possible in DRM case. (This is supported on Apple devices with Fairplay license)
For Android, Dash media(.mpd) can be registered with Widevine DRM license.

If you are trying to use clear Dash / HLS (without DRM) then there is no need to call `registerAsset` API. You can check our [DTGDemo](https://github.com/kaltura/playkit-dtg-android/tree/current/dtgdemo) for Offline/Online Playback funcationality

Please share more details with usecase if you face further issue. For the time, closing this issue.

**Comment by YHossam** [comment]
Thanks a lot I didn't know this.

I have tried a dash file and it worked fine.
